FROM oven/bun:1.2.21-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./tubo.json    ./turbo.json

COPY  ./apps/backend  ./apps/backend

RUN bun install
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run" , "start:backend"]
