
name: Deploy the frontend
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          --build-args:
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: adityajha02/todo-app-frontend:${{ github.sha }}
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.72.20.71 "sudo docker rm -f todo_frontend || true && sudo docker run --name todo_frontend --build-args DATABASE_URL=${{ secrets.DATABASE_URL }} -d -p 3000:3000 adityajha02/todo-app-frontend:${{ github.sha }}"